### PR TITLE
Fixing broken links in README

### PR DESCRIPTION
**Pull request by dharmeshkakadia**

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by dharmeshkakadia** [comment]
I have signed the cla. Do I need to do anything more?

**Comment by nlutsenko** [comment]
Thank you for fixing these!
No need to do anything, we'll just wait for the bot to leave the comment that CLA is signed and i'll merge it in!

**Comment by facebook-github-bot-3** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by nlutsenko** [comment]
Here it is! Merging in now!

**Comment by dharmeshkakadia** [comment]
Thanks @nlutsenko !

**Pull request merged**
